### ISSUE TITLE
`.idea` can be removed

### ISSUE THREAD

**Issue by EnableAsync** [Klaus125/calculator#1]
You may consider not to share the following:

- `.iml` files and `.idea/modules.xml` file for the Gradle or Maven based projects, since these files will be generated on import
- user dictionaries folder (to avoid conflicts if other developer has the same name)

https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by Klaus125** [comment]
thanks for your reminding,I will fix it.👆



 
---Original---
